### ISSUE TITLE
setUseHardwareBatchingIfSupported

### ISSUE THREAD

**Issue by hjjice** [NordicSemiconductor/Android-Scanner-Compat-Library#134]
This interface must be set to true to scan my transparent transmission module，why?

**Comment by philips77** [comment]
Android phones, starting from Android 5 Lollipop, can offload scanning to the Bluetooth controller decreasing power consumption by the main CPU. This, however, has some consequences. When you use `setReportDelay(..)` to some number, the controller should be able to aggregate results and report them in batches. But this depends on the controller, its firmware, capabilities, etc. Different phones with the same Android version may have different controllers chips, so behavior may be different.

Also, we observed, that this method works best when you set the delay to 5 seconds of more. Then we were getting quite reliable results. Unfortunately, some people reported, that with batching some scan results are discarded/not reported. They were getting them with delay = 0 (no batching), but weren't with delay > 0. For that reason, the scanner compat library has an option to emulate batching in CPU using `setUseHardwareBatchingIfSupported(false)`. Under the hood it is using delay = 0, so all results are received, then accumulates it and reported in regular intervals. Mind, that this is not battery-efficient.

Hardware batching is by default enabled if you set delay to > 0, so there's no need to call `setUseHardwareBatchingIfSupported(true)`.

**Comment by hjjice** [comment]
But I found that OPPO and OnePlus can connect when `setUseHardwareBatchingIfSupported(false)` is set. If set to true, the device cannot be connected.

**Comment by hjjice** [comment]
但是   我这样操作之后   居然就可以连接了   实在不懂了：
settings
                    .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                    .setReportDelay(0)
                scanner.startScan(null, settings.build(), scanCallback)
                scannerState?.scanningStarted()
                Thread.sleep(1500)
                stopScan()
                Thread.sleep(1000)
                settings.setReportDelay(100)
                scanner.startScan(null, settings.build(), scanCallback)
                scannerState?.scanningStarted()

**Comment by hjjice** [comment]
But after I did this, I was able to connect. I really don’t understand:
```kotlin
settings
   .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
   .setReportDelay(0)
scanner.startScan(null, settings.build(), scanCallback)
scannerState?.scanningStarted()
Thread.sleep(1500)
stopScan()
Thread.sleep(1000)
settings.setReportDelay(100)
scanner.startScan(null, settings.build(), scanCallback)
scannerState?.scanningStarted()
```

**Comment by philips77** [comment]
It may have a relation with how the Android caches the address type. 
As you may know, the Bluetooth address is 49 bit long. 49, not 48? Yes. The 49th bit is the address type, which may be *private* or *public*. Public addresses are registered by IEEE and accessible on their [website](https://regauth.standards.ieee.org/standards-ra-web/pub/view.html).

More about this here: https://novelbits.io/bluetooth-address-privacy-ble/

However, up until API 33 this last bit was not given explicitly to the API. This has changed with the introduction of [`getRemoteLeDevice(address, type)`](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#getRemoteLeDevice(java.lang.String,%20int)) method and now in *androidx.bluetooth* library, which also has minSdk=33.

Until API 32 the address type had to be scanned and was assumed *public* otherwise, although most devices use random addresses. When Android scanned a packet from a new MAC address it was storing its type in a local database and when the user requested connection to a `BluetoothDevice` containing a 48-bit address, it was taking the type from there. That's why it's not possible to connect to a previously scanned device after toggling Bluetooth off and on. The database gets cleared and again a public address is assumed. The address type of bonded devices is stored permanently.

A *Connect Indication* request also contains 49-bit long address, so trying to connect to a valid 48-bit long address with a wrong type flag will fail.

Perhaps, scanning with a delay, which is offloaded to the controller, does not update the local database, hence Android awaits an advertising packet form a public address before sending Connection Indication. Only when the report delay is 0 and the packet is scanned  the list gets updated and following connections work. That is my assumption.

Also, we found that the `setReportDelay(..)` works best with delays 5 seconds or more, not 100 ms. Only then we were able to get true intervals or given length.
