### ISSUE TITLE
BT Adapter is not turned ON

### ISSUE THREAD

**Issue by hearsilent** [NordicSemiconductor/Android-Scanner-Compat-Library#27]
I got this crash, I've check BT is on by `mBluetoothAdapter.isEnabled()`.
It's seems like sometimes `mBluetoothAdapter.isEnabled()` not the same `mBluetoothAdapter.getState() == BluetoothAdapter.STATE_ON`.

Do you have any suggestions?

Thx!

> Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at no.nordicsemi.android.support.v18.scanner.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:137)
       at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplLollipop.startScanInternal(BluetoothLeScannerImplLollipop.java:64)
       at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.startScan(BluetoothLeScannerCompat.java:123)

**Comment by NeoSyder** [comment]
Hi, I had the same issue than @hearsilent. I can't verify if the adapter is null of its state different from
`BluetoothAdapter.STATE_ON` from `checkAdapterStateOn(BluetoothAdapter adapter)` because it was received on a phone with Raygun (= crashlytics).

I tried to invoke bluetoothAdapter from BluetoothManager instead of `BluetoothAdapter.getDefaultAdapter()` and there seems to be no difference.

**Comment by philips77** [comment]
I guess what you experience here is the system trying to recover from a fault by restarting Bluetooth. Since Marshmallow, or maybe before, Android restarts Bluetooth on its own when something bad happen to it. So perhaps, when the method was started, the Bluetooth was ON, but moment later got disabled. I can't see any other reason. And I'm not sure there is any solution for that other than putting it into `try-catch` block.

**Comment by NeoSyder** [comment]
Thank you for your response, this is what I thought, I was going to use a `try-catch` block.
