### ISSUE TITLE
In Android 9 and 10 if use filter peer not found on scan process

### ISSUE THREAD

**Issue by LebetsVI** [NordicSemiconductor/Android-Scanner-Compat-Library#67]
Hi.
Using this lib, I came across an unpleasant thing: if I set  filter like as:

_final List<ScanFilter> filters = new ArrayList<>();
filters.add(new ScanFilter.Builder().setDeviceName(KNOWN_DEV_NAME).build());
scanner.startScan(filters, settings, scanCallback);_

then scanner do not return result and stop by timeout. 

Any settings for "setScanMode" do not give a result.

When don`t use filter: all ok.

Code example:
_**final BluetoothLeScannerCompat scanner = BluetoothLeScannerCompat.getScanner();
final ScanSettings settings = new ScanSettings.Builder()
                .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                .setReportDelay(500)
                .build();
final List<ScanFilter> filters = new ArrayList<>();
filters.add(new ScanFilter.Builder().setDeviceName(working_device_name).build());
scanner.startScan(filters, settings, scanCallback);**_

**Comment by philips77** [comment]
Hi,
Sorry for 1.5 year delay. Did you manage to solve the issue?
I know that offloaded filtering not always works, that's why we have
https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library/blob/e56d7f134600ee10f611660d53ff3040c08e463e/scanner/src/main/java/no/nordicsemi/android/support/v18/scanner/ScanSettings.java#L499-L514 flag to emulate filtering in the code (which uses much more battery).

**Comment by LebetsVI** [comment]
Hi.
I set "ScanSettings" with "setUseHardwareFilteringIfSupported(**false**)", don`t use lib-embedded filtering and use our custom filter in advertising packets.
