### ISSUE TITLE
onDeviceConnecting -> onDeviceDisconnected -> onError

### ISSUE THREAD

**Issue by netcyrax** [NordicSemiconductor/Android-Scanner-Compat-Library#82]
Hello,

I am consistently getting this order of callbacks:

onDeviceConnecting -> onDeviceDisconnected -> onError ("Error on connection state change", 133) 

Not sure why, but when debugging and I am adding random pauses between calls the device gets connected and proceeds as it should. Any ideas?

Thanks.

**Comment by philips77** [comment]
Hello,
First of all, your question isn't related to Android Scanner Combat Library, as this library only supports scanning. Connection can be done using native API, or [Android BLE Library](https://github.com/NordicSemiconductor/Android-BLE-Library), that we recommend.

Coming back to your question, you should be able to find tons of cases like this on Stack Overflow or BLE library issues. Error 133 is a generic GATT error indicating that "something went wrong". If the error is thrown around 30 after the connection attempt, this indicates a timeout. That means your device isn't in range, is advertising as non-connectable, or doesn't respond to connection request. If the error happens around 4 seconds after you call `connectGatt(...)`, that probably means that the Connect Request packet has been missed by your device and it continues to advertise instead of accepting connection. This however, should not happen "consistently", but rather from time to time, and the following or 2 connection attempts should succeed. When using BLE Library, you may call `retry(number of retries, interval)` method in [ConnectRequest](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/e95a814f4c0ecd08a75e5f0e53c68e2b8dbdf70c/ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java#L160), which should handle this automatically.
When you get this error immediately, and consistently, that means that there's either a problem with Bluetooth stack on the phone (you may try connecting to your device using nRF Connect for Android and trying clearing device cache, then trying again with app, or restarting Bluetooth or your phone), or the device. You may also try a different phone, to check if it's the device, or this phone. It's very hard to determine the root cause of each 133 error.
